//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Percent
    {
        public int IdUser { get; set; }
        public Nullable<int> PercentTopic { get; set; }
        public Nullable<int> PercentTest { get; set; }
        public Nullable<int> PercentTask { get; set; }
    }
}
