//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int IDTask { get; set; }
        public int TopicTask { get; set; }
        public string TitleTask { get; set; }
        public string PracticalTask { get; set; }
        public System.DateTime LastDateTask { get; set; }
    }
}
