//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int IdTest { get; set; }
        public string TopicTest { get; set; }
        public string TitleTest { get; set; }
        public string JsonFile { get; set; }
    }
}
