//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int IDTopic { get; set; }
        public string TitleTopic { get; set; }
        public string DescriptionTopic { get; set; }
        public string LectureTopic { get; set; }
        public string UrlVideoTopic { get; set; }
    }
}
